# Check-And-Start.ps1
# Verify the project is healthy, then start the dev preview server.
# Self-contained per Agent Working Agreement §10.
#
# Usage (from anywhere — the script figures out its own path):
#   .\Check-And-Start.ps1

$ErrorActionPreference = "Continue"  # keep going on non-fatal warnings
$root = Split-Path -Parent $MyInvocation.MyCommand.Definition
Set-Location $root

function Header($t) { Write-Host ""; Write-Host $t -ForegroundColor Cyan; Write-Host ("=" * $t.Length) -ForegroundColor Cyan }
function Pass($t)   { Write-Host ("  [OK]   " + $t) -ForegroundColor Green }
function Warn($t)   { Write-Host ("  [warn] " + $t) -ForegroundColor Yellow }
function Fail($t)   { Write-Host ("  [FAIL] " + $t) -ForegroundColor Red }
function Info($t)   { Write-Host ("  " + $t) -ForegroundColor DarkGray }

$problems = @()

# ---------------------------------------------------------------------------
Header "1/8  Project folder & expected files"

$expected = @(
  "scripts\build.py",
  "scripts\common.py",
  "scripts\dev_server.py",
  "scripts\pages\__init__.py",
  "site\assets\css\site.css",
  "site\assets\js\site.js",
  "site\assets\img\favicon.svg",
  ".github\workflows\deploy.yml",
  "Run-Dev.ps1",
  "Stop-Dev.ps1",
  "Restart-Dev.ps1",
  "Refresh-Media.ps1",
  "Publish-Site.ps1",
  "Init-Repo.ps1",
  "LICENSE",
  "NOTICE",
  "README.md",
  "CHANGELOG.md",
  "VERSION"
)
foreach ($f in $expected) {
  if (Test-Path $f) { Pass $f } else { Fail "missing: $f"; $problems += $f }
}

# Page module count
$pageMods = Get-ChildItem "scripts\pages\_*.py" -ErrorAction SilentlyContinue
if ($pageMods.Count -ge 8) { Pass "scripts\pages\ contains $($pageMods.Count) page modules" }
else { Warn "scripts\pages\ has only $($pageMods.Count) page modules (expected 9+)" }

# ---------------------------------------------------------------------------
Header "2/8  Generated HTML pages"

$htmlCount = (Get-ChildItem "site" -Recurse -Filter "*.html" -ErrorAction SilentlyContinue).Count
if ($htmlCount -ge 20) { Pass "site\ contains $htmlCount HTML pages" }
elseif ($htmlCount -gt 0) { Warn "site\ contains only $htmlCount HTML pages (run a rebuild)" }
else { Fail "site\ has no HTML pages — needs a build" }

# ---------------------------------------------------------------------------
Header "3/8  Media assets"

$audioFiles = Get-ChildItem "site\assets\audio" -Filter "track-*" -ErrorAction SilentlyContinue
$videoFiles = Get-ChildItem "site\assets\video" -Filter "hero-*" -ErrorAction SilentlyContinue
if ($audioFiles.Count -gt 0) {
  $tot = ($audioFiles | Measure-Object Length -Sum).Sum / 1MB
  Pass ("audio: {0} tracks, {1:N1} MB total" -f $audioFiles.Count, $tot)
} else { Warn "no audio tracks under site\assets\audio\" }
if ($videoFiles.Count -gt 0) {
  $tot = ($videoFiles | Measure-Object Length -Sum).Sum / 1MB
  Pass ("video: {0} clips, {1:N1} MB total" -f $videoFiles.Count, $tot)
} else { Warn "no hero videos under site\assets\video\" }

$manifest = "site\assets\js\media-manifest.js"
if (Test-Path $manifest) { Pass "media-manifest.js present" }
else { Warn "media-manifest.js missing — will be regenerated by build" }

# ---------------------------------------------------------------------------
Header "4/8  Python (the only required runtime)"

$python = (Get-Command python -ErrorAction SilentlyContinue).Source
if (-not $python) { $python = (Get-Command python3 -ErrorAction SilentlyContinue).Source }
if ($python) {
  $ver = & $python --version 2>&1
  Pass "python: $ver  ($python)"
} else { Fail "no python on PATH — install from https://python.org"; $problems += "python" }

# ---------------------------------------------------------------------------
Header "5/8  Git & GitHub remote"

try {
  $gitV = git --version 2>$null
  Pass "git: $gitV"
} catch { Warn "git not installed (only needed when publishing)" }

if (Test-Path ".git") {
  $branch = git rev-parse --abbrev-ref HEAD 2>$null
  Pass "git repo initialised on branch: $branch"
  $remote = git remote get-url origin 2>$null
  if ($remote) { Pass "remote origin: $remote" } else { Warn "no remote origin set (run Init-Repo.ps1)" }
  $tag = git describe --tags --abbrev=0 2>$null
  if ($tag) { Pass "latest tag: $tag" }
} else {
  Warn ".git/ not present — repo not initialised yet (run Init-Repo.ps1 when ready to publish)"
}

try {
  $ghV = (gh --version 2>$null | Select-Object -First 1)
  if ($ghV) { Pass "gh CLI: $ghV" }
} catch { Info "gh CLI not installed (optional — only used for one-shot publish)" }

# ---------------------------------------------------------------------------
Header "6/8  Preview-server state (any stale instance)"

if (Test-Path ".preview-pid") {
  $line = Get-Content ".preview-pid" | Select-Object -First 1
  $oldPid = ($line -split ' ')[0]
  $proc = Get-Process -Id $oldPid -ErrorAction SilentlyContinue
  if ($proc) {
    Warn "stale preview server running (PID $oldPid) — will be stopped before restart"
  } else {
    Info "stale .preview-pid file (process $oldPid no longer running) — will be cleaned up"
    Remove-Item ".preview-pid" -ErrorAction SilentlyContinue
  }
} else {
  Pass "no stale preview server"
}

# ---------------------------------------------------------------------------
Header "7/8  Disk / repo size"

$totalBytes = 0
Get-ChildItem -Recurse -Force -ErrorAction SilentlyContinue |
  Where-Object { -not $_.PSIsContainer -and $_.FullName -notmatch "\\\.git\\" } |
  ForEach-Object { $totalBytes += $_.Length }
Pass ("total tracked content: {0:N1} MB" -f ($totalBytes/1MB))

# ---------------------------------------------------------------------------
Header "8/8  Summary"

if ($problems.Count -eq 0) {
  Write-Host "  All checks passed. Starting preview server next." -ForegroundColor Green
} else {
  Write-Host "  $($problems.Count) issue(s) detected — see [FAIL] lines above." -ForegroundColor Yellow
  Write-Host "  Continuing to start preview; fix above issues if anything misbehaves." -ForegroundColor Yellow
}

# ---------------------------------------------------------------------------
# Start the dev server via the existing Restart-Dev.ps1 (rebuilds + stops any
# stale server + starts a fresh one on the first free port).
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "Starting preview server..." -ForegroundColor Cyan
& (Join-Path $root "Restart-Dev.ps1")
