#!/usr/bin/env python3
"""
Mira Palace demo-site generator.

Reads page definitions from ./pages/*.py and renders each to ../site/*.html
using a shared template + nav + footer.

Run from the project root:
    python scripts/build.py
"""

from __future__ import annotations
import importlib, pathlib, sys, datetime, json, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SCRIPTS = ROOT / "scripts"
SITE = ROOT / "site"
PAGES_DIR = SCRIPTS / "pages"

sys.path.insert(0, str(SCRIPTS))
from common import render_page, SITE_META, write_media_manifest, VIDEO_OPTIONS, MUSIC_OPTIONS  # noqa: E402

# ---- Discover and render every page module -------------------------------

def main() -> None:
    SITE.mkdir(parents=True, exist_ok=True)

    # Static assets: css/js/favicon live under site/assets/ — already committed;
    # this script only (re)writes the HTML pages.

    modules = sorted(p.stem for p in PAGES_DIR.glob("*.py") if p.stem != "__init__")
    count = 0
    all_pages = []
    for mod_name in modules:
        mod = importlib.import_module(f"pages.{mod_name}")
        for page in mod.PAGES:
            out_path = SITE / page["path"]
            out_path.parent.mkdir(parents=True, exist_ok=True)
            html = render_page(page)
            out_path.write_text(html, encoding="utf-8")
            count += 1
            all_pages.append((page, html))
            print(f"  {page['path']}")

    # Media manifest — every video / track found on disk goes into a JS file
    # the browser loads before site.js
    manifest_path = SITE / "assets" / "js" / "media-manifest.js"
    write_media_manifest(manifest_path)
    n_vid = sum(1 for k, _, _ in VIDEO_OPTIONS if k != "none")
    n_aud = sum(1 for k, _, _ in MUSIC_OPTIONS if k != "none")
    print(f"  assets/js/media-manifest.js  ({n_vid} videos, {n_aud} tracks)")

    # Search index — per-page record of title + description + headings.
    # site.js reads window.MIRA_SEARCH_INDEX to power the nav search popup.
    build_search_index(all_pages)
    print(f"  assets/js/search-index.js  ({len(all_pages)} pages indexed)")

    # Sitemap
    build_sitemap()

    print(f"\nGenerated {count} pages.")
    print(f"Site root: {SITE}")


def build_search_index(all_pages) -> None:
    """Extract a lightweight search record from every page.

    For each page we collect: path, title, description, and a flat list of
    section headings (h1/h2/h3 inner text). Body text is intentionally
    excluded — this keeps the index small and matches what most guests
    actually search for (sections, not paragraphs)."""
    index = []
    h_re = re.compile(r"<h[1-3][^>]*>(.*?)</h[1-3]>", re.IGNORECASE | re.DOTALL)
    tag_re = re.compile(r"<[^>]+>")
    ws_re = re.compile(r"\s+")
    entity_re = re.compile(r"&[a-z#0-9]+;", re.IGNORECASE)
    for page, html in all_pages:
        # Strip header/footer (everything inside <main>) so search doesn't
        # match the nav labels on every single page.
        m = re.search(r"<main[^>]*>(.*)</main>", html, re.DOTALL)
        body = m.group(1) if m else html
        headings = []
        for raw in h_re.findall(body):
            clean = tag_re.sub("", raw)
            clean = entity_re.sub(" ", clean)
            clean = ws_re.sub(" ", clean).strip()
            if clean and clean not in headings:
                headings.append(clean)
        # Build a clean URL — strip "index.html"
        url = page["path"]
        if url == "index.html":
            url = ""
        elif url.endswith("/index.html"):
            url = url[:-10]
        index.append({
            "path": url,
            "title": page["title"],
            "description": page.get("description", ""),
            "headings": headings[:8],   # cap at 8 per page to keep the index small
        })
    out = SITE / "assets" / "js" / "search-index.js"
    js = (
        "// Auto-generated by scripts/build.py — do not edit by hand.\n"
        "// One record per page: path, title, description, top headings.\n"
        f"window.MIRA_SEARCH_INDEX = {json.dumps(index, ensure_ascii=False, indent=2)};\n"
    )
    out.write_text(js, encoding="utf-8")


def build_sitemap() -> None:
    base = SITE_META["base_url"].rstrip("/")
    urls = []
    for p in sorted(SITE.rglob("*.html")):
        if p.name == "404.html":
            continue
        rel = p.relative_to(SITE).as_posix()
        if rel == "index.html":
            rel = ""
        elif rel.endswith("/index.html"):
            rel = rel[:-10]
        urls.append(f"{base}/{rel}")

    sitemap = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    today = datetime.date.today().isoformat()
    for u in urls:
        sitemap += f"  <url><loc>{u}</loc><lastmod>{today}</lastmod></url>\n"
    sitemap += "</urlset>\n"
    (SITE / "sitemap.xml").write_text(sitemap, encoding="utf-8")

    # Demo site: keep crawlers out. The site is technically public on a
    # GitHub Pages URL, but we don't want it indexed by Google or scraped
    # while it's still under owner review.
    robots = "User-agent: *\nDisallow: /\n"
    (SITE / "robots.txt").write_text(robots, encoding="utf-8")


if __name__ == "__main__":
    main()
